[package]
name = "nellymoser-rs"
version = "0.1.0"
authors = ["relrelb <relrelbachar@gmail.com>"]
edition = "2018"
description = "Nellymoser decoding library written in Rust"
license = "MIT"

[dependencies]
bitstream-io = "1.0.0"
rustdct = "0.6.0"
